require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true

  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'project_files/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'Guardfile'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  IgnoredPatterns: ['\A\s*#']

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Metrics/BlockLength:
  ExcludedMethods:
    - describe
